name: rockbreakers
services:
    ayame:
        image: golang:1.22
        working_dir: /usr/src/myapp
        command: bash -c "(/usr/src/myapp/bin/ayame) || (git clone https://github.com/OpenAyame/ayame.git) && (mv ./ayame/* ./) && (ls -al) && (go install) && make && (make init) && /usr/src/myapp/bin/ayame"
        ports:
            - 3000:3000
